### ISSUE TITLE
Menus break in threads

### ISSUE THREAD

**Issue by Skelmis** [nextcord/nextcord-ext-menus#28]
```python
        pages = menus.ButtonMenuPages(
            source=EvalPageSource(bot, result, ctx.author),
            clear_buttons_after=True,
        )
        await pages.start(ctx)
```

Will throw the following error when used in a thread.
``AttributeError: 'Thread' object has no attribute '_overwrites'``

**Comment by DenverCoder1** [comment]
I can't seem to reproduce this issue.

All examples of menus I have tried are working in threads.

**Comment by DenverCoder1** [comment]
Has this been resolved?
